#!/bin/bash

cd `dirname $0`

echo 进入`pwd`
echo -n 请指定安装路径，默认为\ /env：
read base

function checkInstall ()
{
    if [ ! -d $1/$2 ] ; then
        exit 1
    fi
}

echo 开始安装

if [ ! $base ] ; then
    base=/env
fi
sudo mkdir -p $base

#安装
build/install/nginx $base/nginx
checkInstall $base nginx

build/install/php $base/php
checkInstall $base php

build/install/redis $base/redis

build/install/phpredis $base/php

build/install/composer

echo 安装完成
build/shell/cleanpkg
